### ISSUE TITLE
Crashes immediately on start

### ISSUE THREAD

**Issue by ro-savage** [dwalkr/next-tina-blog-starter#1]
I cloned this repo and installed, and when I `yarn dev` and try load the page I immediately get the error 

```
[ ready ] compiled successfully - ready on http://localhost:3000
Error: No valid exports main found for '/Users/rowan/www/next/next-tina-blog-starter/node_modules/w3c-keyname'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/rowan/www/next/next-tina-blog-starter/node_modules/prosemirror-keymap/dist/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/rowan/www/next/next-tina-blog-starter/node_modules/prosemirror-gapcursor/dist/index.js:5:25) {
  code: 'MODULE_NOT_FOUND'
}
[ event ] build page: /next/dist/pages/_error
```

Upgrading to tinacms 0.20 and and next 9.4.4 fixed this.

**Comment by dwalkr** [comment]
fixed in https://github.com/dwalkr/next-tina-blog-starter/pull/5
